# Generated by Django 4.2.28 on 2026-03-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to an image/logo for this course (e.g. Python logo)', null=True),
        ),
    ]
