# Generated by Django 4.2.28 on 2026-03-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
